# Generated by Django 3.2.12 on 2022-05-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmisionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=100)),
                ('fathare_name', models.CharField(max_length=100)),
                ('Phone_Number', models.IntegerField()),
                ('adhar_number', models.IntegerField()),
                ('Address', models.TextField()),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
