# Generated by Django 3.2.12 on 2022-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_addmisionform_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmisionform',
            name='photo',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='images'),
        ),
    ]
