# Generated by Django 3.2.12 on 2022-05-30 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_addmisionform_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmisionform',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
